### ISSUE TITLE
Code Structuring

### ISSUE THREAD

**Issue by nandhinianandhan** [dipeshsingh253/excellent-noise-5475#3]
https://github.com/dipeshsingh253/excellent-noise-5475/blob/08a4f5d2b3dfbe24e02f4ba5b656170c72db4840/src/com/mgnrega/driver/Main.java#L71

Instead of creating variable here, create the variable in a class and use the object references here

**Comment by dipeshsingh253** [comment]
Here I have initialization variables so I can take input from the user and pass it through the constructor so I can create a new object on the basis of the given input by the user. I'm using final because I don't want to reassign any new value after users input.
